name: Autocomplete Pull
on: push

jobs: 
  build: 
    runs-on: windows-latest
    strategy: 
      matrix:
        python-version: [3.14]

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies [pip]
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
