name: google-autocomplete-pull
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Install dependencies [pip]
        run: |
          python -m pip install pip --upgrade pip
          pip install -r requirements.txt
           
      - name: Pull suggests from Google 
        run: |
          python main.py
      - name: commit
        run: |
          # Stage the file, commit and push
          git config user.email "naca4005@colorado.edu"
          git config user.name "NatalieRMCastro"
          git pull
          git add *
          git commit -m "completed pull for `date +'%Y-%m-%d'`" || exit 0
          git push
